Feature/upgrade
aragon/core pull request #202
Opened 2023-01-19 09:45 UTC by novaknole

## Description

Please include a summary of the change and be sure you follow the contributions rules we do provide [here](./CONTRIBUTIONS.md)

Task: [ID]()

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [ ] I have tested my code on the test network.

2023-01-20 08:05 UTC, mathewmeconry requested changes

2023-01-20 08:05 UTC, mathewmeconry commented on packages/contracts/contracts/voting/admin/Admin.sol
> +
whitespace

2023-01-20 08:05 UTC, mathewmeconry commented on packages/contracts/test/test-utils/error.ts
> +import { ethers } from "hardhat";
formatting. should be `{ethers}`

2023-01-20 08:05 UTC, mathewmeconry commented on packages/contracts/test/voting/addresslist-voting.ts
> +import { deployWithProxy } from '../test-utils/proxy';
formatting

2023-01-20 08:05 UTC, mathewmeconry commented on packages/contracts/test/voting/admin.ts
> +import {deployWithProxy} from '../test-utils/proxy';
remove unecessary import

2023-01-20 15:02 UTC, mathewmeconry approved these changes

2023-01-25 07:52 UTC, mathewmeconry approved these changes

2023-01-25 08:49 UTC, Michael-A-Heuer approved these changes

2023-01-27 11:07 UTC, brickpop commented on packages/contracts/test/core/dao.ts
> +    this.upgrade = {
- Does this test have side effects?
- Are we using this data anywhere?

2023-01-27 11:07 UTC, brickpop commented on packages/contracts/test/test-utils/error.ts
> +import {ethers} from 'hardhat';
Is this import used anywhere?

2023-01-27 11:41 UTC, brickpop submitted a review, later dismissed

2023-01-27 11:47 UTC, brickpop approved these changes

2023-01-27 12:47 UTC, brickpop approved these changes

2023-01-27 12:51 UTC, mathewmeconry approved these changes

2023-01-27 12:52 UTC, merged