Do `_disableInitializers` inside `PluginCloneable` and `PluginUUPSUpgradeable`
aragon/core pull request #257
Opened 2023-02-13 10:39 UTC by Michael-A-Heuer

## Description

Best practice by OZ and auditor suggestions recommend to call  `_disableInitializers` for proxy contracts to not leave them uninitialized. 
This PR moves `_disableInitializers` inside `PluginCloneable` and `PluginUUPSUpgradeable` constructors so that people cannot accidentally forget.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [x] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

2023-02-20 12:53 UTC, mathewmeconry requested changes

2023-02-20 12:53 UTC, mathewmeconry commented on packages/contracts/src/test/plugin/AdminCloneFactory.sol
> +import {Admin} from "../../plugins/governance//admin/Admin.sol";
```suggestion
import {Admin} from "../../plugins/governance/admin/Admin.sol";
```

2023-02-21 09:22 UTC, mathewmeconry submitted a review, later dismissed

2023-02-21 15:40 UTC, mathewmeconry approved these changes

2023-02-21 16:56 UTC, novaknole approved these changes

2023-02-21 16:56 UTC, merged